export const BUTTON_TYPES = {
  NORMAL_TRANSPARENT: "NORMAL_TRANSPARENT",
  SMALL_BLUE: "SMALL_BLUE",
  SMALL_TRANSPARENT: "SMALL_TRANSPARENT",
  NORMAL_CANCEL: "NORMAL_CANCEL",
  NORMAL_CONFIRM: "NORMAL_CONFIRM",
};
